[build]
target-dir = "target"
rustflags = ["--cfg", "tokio_unstable"]
#rustc-wrapper = "sccache"

[env]
SENTRY_DSN = { value = "PLEASE DEFINE AT COMPILE TIME" }
# Scope unstable standard-library APIs to clash-lib only.
RUSTC_BOOTSTRAP = { value = "clash_lib" }

[target.x86_64-pc-windows-msvc]
linker = "link.exe"
rustflags = ["-C", "link-arg=/threads:0"]
